[package]
name = "treasury-import"
version = "0.1.0"
authors = ["Zakarum <zakarumych@ya.ru>"]
edition = "2018"

[features]
ffi = []
default = ["ffi"]

[dependencies]
uuid = { version = "0.8" }
eyre = "0.6"
