[package]
name = "dummy"
version = "0.1.0"
authors = ["Zakarum <zakarumych@ya.ru>"]
edition = "2018"
publish = false

[lib]
crate-type = ["dylib"]

[dependencies]
treasury-import = { path = "../import" }
